language: go
go:
 - tip

services:

before_install:
# - go get github.com/mattn/goveralls

script:
 - go vet -x ./...
 - $HOME/gopath/bin/golint ./...
 - go test -v ./...
 - go test -covermode=count -coverprofile=profile.cov .
 - go tool cover -func=profile.cov

#after_script:
#- $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
